# Generated by Django 3.1.13 on 2021-11-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='wait',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='recent_access_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
