# Generated by Django 3.1.13 on 2021-11-06 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0003_remove_visitor_wait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='recent_access_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
